//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by alxBASE.rc
//

// Extended error codes
#define ALX_PRS_ERROR_MIN						3200
#define ALX_PRS_ERROR_SYNTAX_ERROR				ALX_PRS_ERROR_MIN + 1
#define ALX_PRS_ERROR_MISSING					ALX_PRS_ERROR_MIN + 2
#define ALX_PRS_ERROR_DATATYPE_MISMATCH			ALX_PRS_ERROR_MIN + 3
#define ALX_PRS_ERROR_OPERAND_MISMATCH			ALX_PRS_ERROR_MIN + 4
#define ALX_PRS_ERROR_ARGTYPE_MISMATCH			ALX_PRS_ERROR_MIN + 5
#define ALX_PRS_ERROR_VARIABLE_NOT_FOUND		ALX_PRS_ERROR_MIN + 6
#define ALX_PRS_ERROR_FUNCTION_NOT_FOUND		ALX_PRS_ERROR_MIN + 7
#define ALX_PRS_ERROR_TOO_FEW_ARGUMENTS			ALX_PRS_ERROR_MIN + 8
#define ALX_PRS_ERROR_TOO_MANY_ARGUMENTS		ALX_PRS_ERROR_MIN + 9
#define ALX_PRS_ERROR_INVALID_ARGUMENT			ALX_PRS_ERROR_MIN + 10
#define ALX_PRS_ERROR_INVALID_ARGUMENT_SQRT		ALX_PRS_ERROR_MIN + 11
#define ALX_PRS_ERROR_INVALID_ARGUMENT_LOG		ALX_PRS_ERROR_MIN + 12
#define ALX_PRS_ERROR_INVALID_ARGUMENT_LOG10	ALX_PRS_ERROR_MIN + 13
#define ALX_PRS_ERROR_INVALID_ARGUMENT_CTOT		ALX_PRS_ERROR_MIN + 14
#define ALX_PRS_ERROR_DEVIDE_BY_ZERO			ALX_PRS_ERROR_MIN + 15
#define ALX_PRS_ERROR_EXP_DOMAIN_ERROR			ALX_PRS_ERROR_MIN + 16
#define ALX_PRS_ERROR_MISSING_OPERAND			ALX_PRS_ERROR_MIN + 17
#define ALX_PRS_ERROR_FUNCTION_MISSING			ALX_PRS_ERROR_MIN + 18
#define ALX_PRS_ERROR_MISSING_EXPR				ALX_PRS_ERROR_MIN + 19
#define ALX_PRS_ERROR_MISSING_OPERATOR			ALX_PRS_ERROR_MIN + 20
#define ALX_PRS_ERROR_MAX						ALX_PRS_ERROR_MIN + 20

