//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by alxBASE.rc
//

// Extended error codes
#define NO_ALX_DBF_ERROR                        0
#define ALX_DBF_ERROR_MIN                       3000
#define ALX_DBF_ERROR                           ALX_DBF_ERROR_MIN
#define ALX_DBF_ERROR_DBFILE_CREATE		        ALX_DBF_ERROR+1
#define ALX_DBF_ERROR_DBFILE_OPEN		        ALX_DBF_ERROR+2
#define ALX_DBF_ERROR_DBFILE_MEMORYLOAD			ALX_DBF_ERROR+3
#define ALX_DBF_ERROR_DBFHEADER_READ			ALX_DBF_ERROR+4
#define ALX_DBF_ERROR_DBFHEADER_WRITE			ALX_DBF_ERROR+5
#define ALX_DBF_ERROR_NOT_TABLE					ALX_DBF_ERROR+6
#define ALX_DBF_ERROR_NOT_FIELDS				ALX_DBF_ERROR+7
#define ALX_DBF_ERROR_FILE_SIZE					ALX_DBF_ERROR+8
#define ALX_DBF_ERROR_FIELDS_READ				ALX_DBF_ERROR+9
#define ALX_DBF_ERROR_MEMO_CREATE				ALX_DBF_ERROR+10
#define ALX_DBF_ERROR_MEMO_OPEN					ALX_DBF_ERROR+11
#define ALX_DBF_ERROR_MEMO_HEAD_READ			ALX_DBF_ERROR+12
#define ALX_DBF_ERROR_MEMO_BLOCK_SIZE			ALX_DBF_ERROR+13
#define ALX_DBF_ERROR_MEMO_FIELD_READ			ALX_DBF_ERROR+14
#define ALX_DBF_ERROR_MEMO_FIELD_WRITE			ALX_DBF_ERROR+15
#define ALX_DBF_ERROR_MEMO_RECORD_READ			ALX_DBF_ERROR+16
#define ALX_DBF_ERROR_MEMO_RECORD_WRITE			ALX_DBF_ERROR+17
#define ALX_DBF_ERROR_RECORD_OUTOFRANGE			ALX_DBF_ERROR+18
#define ALX_DBF_ERROR_RECORD_READ				ALX_DBF_ERROR+19
#define ALX_DBF_ERROR_RECORD_WRITE				ALX_DBF_ERROR+20
// Find error
#define ALX_DBF_ERROR_NOT_LOGIC_EXPR			ALX_DBF_ERROR+21

#define ALX_DBF_ERROR_MAX                       ALX_DBF_ERROR+21


